In [1]:
import numpy as np
from math import sqrt

In [2]:
#Diagonallly Dominenant

def check_Diagonal_Dominent(m, n) :
    for i in range(0, n) :
        sum = 0
        for j in range(0, n) :
            sum = sum + abs(m[i][j])    
        sum = sum - abs(m[i][i])
        if (abs(m[i][i]) < sum) :
            return False
 
    return True

In [3]:
def make_Diagonali_Dominent(D):
    A=np.array((D),dtype=float)
    n = len(A[0])
    flag  = False
    for i in range(0,n-1):     
        sum = np.sum(np.abs(A[i,]))
        sum = sum - np.abs(A[i,i])
        if np.abs(A[i,i]) < sum:
            for k in range(i+1,n):
                sum = np.sum(np.abs(A[k,]))
                sum = sum - np.abs(A[k,i])
                if np.abs(A[k,i]) > sum:
                    A[[i,k]]=A[[k,i]] 
                    print("Swap %d with %d "%(i,k))
                    flag = True
                    break
                else:
                    flag = False
                    return A,"Not Possible to make DD"
        
    return A,"It's Possible Make it DD"

In [4]:
A = np.array([[100,3,5,4],
              [1,9,1,4],
              [6,7,3,20],
              [5,7,17,1]])
print(A)
s = check_Diagonal_Dominent(A,len(A))
if not s :
    print("Not Dominant")
    A = make_Diagonali_Dominent(A)
    print(A[1])
    print(A[0])
    
else :
    print("Is Diagonally Dominant")

[[100   3   5   4]
 [  1   9   1   4]
 [  6   7   3  20]
 [  5   7  17   1]]
Not Dominant
Swap 2 with 3 
It's Possible Make it DD
[[100.   3.   5.   4.]
 [  1.   9.   1.   4.]
 [  5.   7.  17.   1.]
 [  6.   7.   3.  20.]]
